#security
login_check:
    path: /login_check

logout:
    path: /logout

login:
    path: /login
    defaults: { _controller: MrsuhRealEstateBundle:Security:login }


#default
default:
    path: /default
    defaults: { _controller: MrsuhRealEstateBundle:Default:default }

#redirect
redirect:
    path: /
    defaults: { _controller: MrsuhRealEstateBundle:Default:redirect }


# profile
profile:
    path: /profile
    defaults: { _controller: MrsuhRealEstateBundle:User:profile }

#clients
client:
    path: /client/{id}
    defaults: { _controller: MrsuhRealEstateBundle:Client:getClientById, id: id }

create_client:
    path: /create-client
    defaults: { _controller: MrsuhRealEstateBundle:Client:createClient }

find_client:
    path: /find-client
    defaults: { _controller: MrsuhRealEstateBundle:Client:findClient }

#Advert
advert:
    path: /advert/{id}
    defaults: { _controller: MrsuhRealEstateBundle:Advert:getAdvertById, id: id }

list_advert:
    path: /list-advert
    defaults: { _controller: MrsuhRealEstateBundle:Advert:getListAdvert }

find_advert:
    path: /find-advert
    defaults: { _controller: MrsuhRealEstateBundle:Advert:findAdvert }

create_advert:
    path: /create-advert
    defaults: { _controller: MrsuhRealEstateBundle:Advert:createAdvert }

to_archive_advert:
    path: /to-archive-advert
    defaults: { _controller: MrsuhRealEstateBundle:Advert:toArchiveAdvert }

#Users
user:
    path: /user/{id}
    defaults: { _controller: MrsuhRealEstateBundle:User:user, id: id }

list_user:
    path: /users
    defaults: { _controller: MrsuhRealEstateBundle:User:getListUser }

find_user:
    path: /find-user
    defaults: { _controller: MrsuhRealEstateBundle:User:findUser }

create_user:
    path: /create-user
    defaults: { _controller: MrsuhRealEstateBundle:User:createUser }